### ISSUE TITLE
Can you please use explicit tf-core dependency versioning that matches face-api

### ISSUE THREAD

**Issue by seranus** [justadudewhohacks/tfjs-image-recognition-base#10]
It forces me to use a skipLibCheck and clutters my dependency tree since it will almost always download a higher version of tf-core then required by face-api

This issue is a direct result of that https://github.com/justadudewhohacks/face-api.js/issues/415

Is there any reason why setting an explicit version wouldn't be a good idea?

**Comment by justadudewhohacks** [comment]
> Is there any reason why setting an explicit version wouldn't be a good idea?

The only real reason is that we would enforce other code bases using tfjs-image-recognition-base to use the same tfjs-core version as face-api.js

To be honest, I do not understand, why your package manager does not install the tfjs-core version that is explicitly set in the package.json of face-api.js. Are you using yarn or npm?
